name: Docker ECR & ASG CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 저장소 소스코드 체크아웃
      - name: 소스코드 체크아웃
        uses: actions/checkout@v4

      # Step 2: AWS 자격 증명 구성
      - name: AWS 자격 증명 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # Step 3: Amazon ECR 로그인
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 4: Docker 이미지 빌드 및 ECR 푸시 (HTML 내장)
      - name: Build and push Docker image to ECR
        run: |
          docker build -t 925047940866.dkr.ecr.ap-northeast-2.amazonaws.com/std04/nginx:nginx1.31.3-ecr ./nginx
          docker build -t 925047940866.dkr.ecr.ap-northeast-2.amazonaws.com/std04/nginx:latest ./nginx

          docker push 925047940866.dkr.ecr.ap-northeast-2.amazonaws.com/std04/nginx:nginx1.31.3-ecr
          docker push 925047940866.dkr.ecr.ap-northeast-2.amazonaws.com/std04/nginx:latest

      # Step 5: ASG 인스턴스에 도커 컨테이너 배포
      - name: 프라이빗 인스턴스 컨테이너 배포 (SSM)
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Cicd,Values=asg" \
            --comment "Deploy standalone Nginx Docker container" \
            --parameters 'commands=[
              "systemctl stop nginx || true",
              "aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 925047940866.dkr.ecr.ap-northeast-2.amazonaws.com",
              "docker pull 925047940866.dkr.ecr.ap-northeast-2.amazonaws.com/std04/nginx:latest",
              "docker stop nginx || true",
              "docker rm nginx || true",
              "docker run -d --name nginx -p 80:80 --restart always 925047940866.dkr.ecr.ap-northeast-2.amazonaws.com/std04/nginx:latest",
              "docker image prune -af"
            ]' \
            --region ap-northeast-2